[package]
name = "tpt-gis-io-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tpt-gis-io = { path = ".." }

[[bin]]
name = "geojson"
path = "fuzz_targets/geojson.rs"
test = false
doc = false

[[bin]]
name = "wkb"
path = "fuzz_targets/wkb.rs"
test = false
doc = false

[[bin]]
name = "wkt"
path = "fuzz_targets/wkt.rs"
test = false
doc = false

[[bin]]
name = "shapefile"
path = "fuzz_targets/shapefile.rs"
test = false
doc = false
