[package]
name = "tpt-gis-raster"
description = "Grid data, map algebra, and Cloud Optimized GeoTIFF (COG) parsing for tpt-gis."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true
